# Cache TTL values (in seconds)
CACHE_TTL_DAYS = 30
CACHE_TTL_SECONDS = CACHE_TTL_DAYS * 24 * 3600  # 30 days

PROCESSING_TTL_HOURS = 1
PROCESSING_TTL_SECONDS = PROCESSING_TTL_HOURS * 60 * 60  # 60 minutes

# Cache entry cleanup TTL (in seconds)
CACHE_CLEANUP_TTL_SECONDS = 60

# Rate limiting defaults
DEFAULT_HEALTH_CHECK_RATE_LIMIT_REQUESTS = 1000
DEFAULT_HEALTH_CHECK_RATE_LIMIT_WINDOW = 60

# File size limits (in MB)
DEFAULT_MAX_FILE_SIZE_MB = 100

# Retry configurations
WEBHOOK_RETRY_MAX_ATTEMPTS = 3
WEBHOOK_RETRY_BASE_DELAY = 2  # seconds

# URL path segment extraction
URL_PATH_SEGMENTS_TO_EXTRACT = 2
